server:
    port: 8899
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: mySECURITY_PASS119
        url: jdbc:mysql://192.168.2.124:3306/rsng_topo_edit?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        xa:
            properties:
                useInformationSchema: true
